spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**


        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/companies/**


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
#       defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: eureka-server

